SET TERM !! ;
CREATE TRIGGER SGR_USR0_USUARIO_BI FOR SGR_USR0_USUARIO
ACTIVE BEFORE INSERT POSITION 0
AS
DECLARE VARIABLE tmp DECIMAL(18,0);
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_SGR_USR0_USUARIO_ID, 1);
END!!
SET TERM ; !!


SET TERM ^ ;
CREATE TRIGGER SGR_PRF0_PERFIL_BI FOR SGR_PRF0_PERFIL ACTIVE
BEFORE insert POSITION 0
AS
DECLARE VARIABLE tmp DECIMAL(18,0);
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_SGR_PRF0_PERFIL_ID, 1);
END^
SET TERM ; ^