CREATE INDEX IDX_TRN_TRN0_TRANSACCION_CODIGO ON TRN_TRN0_TRANSACCION (CODIGO);
CREATE INDEX IDX_TRN_TRN0_TRANSACCION_FAFECT ON TRN_TRN0_TRANSACCION (FAFECTA);

CREATE UNIQUE INDEX IDX_TRN_TRN1_TRNEMP_TRN0EMP0 ON TRN_TRN1_TRNEMP (TRN0_ID, EMP0_ID);
CREATE INDEX IDX_TRN_TRN1_TRNEMP_TRN0 ON TRN_TRN1_TRNEMP (TRN0_ID);
CREATE INDEX IDX_TRN_TRN1_TRNEMP_EMP0 ON TRN_TRN1_TRNEMP (EMP0_ID);

CREATE INDEX IDX_TRN_CRR0_CORRELATIVO_CODIGO ON TRN_CRR0_CORRELATIVO (CODIGO);
CREATE INDEX IDX_TRN_CRR0_CORRELATIVO_EMP0 ON TRN_CRR0_CORRELATIVO (EMP0_ID);
CREATE INDEX IDX_TRN_CRR0_CORRELATIVO_SERIE ON TRN_CRR0_CORRELATIVO (SERIE);
CREATE INDEX IDX_TRN_CRR0_CORRELATIVO_INICIA ON TRN_CRR0_CORRELATIVO (INICIAL);
CREATE INDEX IDX_TRN_CRR0_CORRELATIVO_FINAL ON TRN_CRR0_CORRELATIVO (FINAL);
CREATE INDEX IDX_TRN_CRR0_CORRELATIVO_SIGUIE ON TRN_CRR0_CORRELATIVO (SIGUIENTE);





