CREATE GENERATOR GEN_INT_CNT0_CONTINENTE_ID;
CREATE GENERATOR GEN_INT_MND0_MONEDA_ID;
CREATE GENERATOR GEN_INT_PIS0_PAIS_ID;
CREATE GENERATOR GEN_INT_EST0_ESTADO_ID;
CREATE GENERATOR GEN_INT_MNC0_MUNICIPIO_ID;
