CREATE INDEX IDX_INT_CNT0_CONTINENTE ON INT_CNT0_CONTINENTE (CODIGO);
CREATE INDEX IDX_INT_MND0_MONEDA ON INT_MND0_MONEDA (CODIGO);
CREATE INDEX IDX_INT_PIS0_PAIS ON INT_PIS0_PAIS (CODIGO);
CREATE INDEX IDX_INT_EST0_ESTADO ON INT_EST0_ESTADO (CODIGO);
CREATE INDEX IDX_INT_MNC0_MUNICIPIO ON INT_MNC0_MUNICIPIO (CODIGO);


