CREATE INDEX IDX_AXN_CATALOGO_CODIGO ON AXN_CATALOGO (CODIGO);

CREATE INDEX IDX_AXN_DOCUMENTO_Fecha ON AXN_DOCUMENTO(FECHA);
CREATE INDEX IDX_AXN_DOCUMENTO_Serie ON AXN_DOCUMENTO(SERIE);
CREATE INDEX IDX_AXN_DOCUMENTO_Correlativo ON AXN_DOCUMENTO(CORRELATIVO);


